package game;
import java.util.*;
public class GameCharacter {
	protected String uniqueID;
	protected String personality;
	
	
	//default constructor
	
	public GameCharacter() {
		this.uniqueID= "";
		this.personality="";
		
		Random r= new Random();
		r.setSeed(1000);
		int id= r.nextInt(1000);
		setUniqueID(Integer.toString(id));
		setPersonality("NEUTRAL");
		
		
		
	}//end default constructor
	
	public GameCharacter (String uniqueID, String personality) {
		this.uniqueID="uniqueID";
		this.personality="personality";
		
		
		
	}//end preferred constructor
	
	public String reportStructure() {
		StringBuilder sb = new StringBuilder("====================\n");
		sb.append("UniqueID: "+getUniqueID()+"\n");
		sb.append("Personality: "+getPersonality()+"\n");
		sb.append("==================================\n");
		
		return sb.toString();
		
		
		
	}//end reportStracture 
	
	public String getUniqueID() {
		return uniqueID;
	}//end getUniqueID

	/**
	 * Setter for uniqueID
	 * @param name
	 */
	public void setUniqueID(String name) {
		this.uniqueID = name;
	}//end setUniqueID
	
	/**
	 *  Getter for personality
	 * @return
	 */
	public String getPersonality() {
		return personality;
	}//end getPersonality
	
	/**
	 * setter for personality
	 * @param personality
	 */
	public void setPersonality(String personality) {
		this.personality = personality;
	}//setPersonality

	/**
	 * Used for test purposes only using the toString
	 * format generated by Eclipse.
	 */
	@Override
	public String toString() {
		return "GameCharacter [uniqueID=" + uniqueID + ", personality=" + personality + "]";
	}//end toString

	
	
	
	
	

}//end class
